### ISSUE TITLE
Wakatime requires Monodevelop 6.0 but the version in the Ubuntu repositories is only 5.10

### ISSUE THREAD

**Issue by aaronfranke** [CodeCavePro/monodevelop-wakatime#12]
![i](https://cloud.githubusercontent.com/assets/1646875/25152824/f0261c3e-244f-11e7-8729-c2f2e5401c37.png)

Also, the [install guide](https://wakatime.com/help/plugins/monodevelop) refers to versions 5.10 not working which implies that version 5.10 is supported.

**Comment by salaros** [comment]
That's pretty strange, because for MonoDevelop / Xamarin Studio 5.x we left WakaTime 1.0.6 in the addin repository: http://addins.monodevelop.com/Project/Index/183

Anyway you can install MonoDevelop 6.x version on your Ubuntu (and many other Linux distros) by installing flatpak.

```
sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak
flatpak install --user --from https://download.mono-project.com/repo/monodevelop.flatpakref
```

Meanwhile I will investigate on this problem. Probably it is somehow related to [problems Mac users had recently](/CodeCavePro/monodevelop-wakatime/issues/9) and you are seeing a "workaround addin" published by @alanhamlett (probably only for MonoDevelop 6.x versions)

**Comment by salaros** [comment]
Yeah, I confirm that [the addin published](http://addins.monodevelop.com/Project/Index/278) by @alanhamlett is 6.x version only and somehow that new listing overrides the original one.
I will discuss this problem with MonoDevelop team.

**Comment by aaronfranke** [comment]
This is really strange... After downloading `MonoDevelop.WakaTime-1.0.6.mpack` and using MonoDevelop's "Install from file" option, it still tries to install version 2.0.2 somehow! Is the file posted the incorrect version?

![mono](https://cloud.githubusercontent.com/assets/1646875/25203056/69f68a76-251d-11e7-8480-d365c8c0bc46.png)

EDIT: `addin.info` contains `<Addin id="WakaTime" version="2.0.2"` so I think somebody just uploaded the wrong file...

**Comment by salaros** [comment]
That's weired. I've just downloaded and unpacked v1.0.6 addin, it contains the manifest from v2.0.2
It's impossible !physically!, because we haven't touched 5.x addins since March 2016 and 2[.0.x versions were published in August](https://github.com/CodeCavePro/monodevelop-wakatime/commit/ea18f08233d04b1a7ad575840447416415fe9d74)
I will ask MonoDevelop team an explanation for such as behavior on gitter

Meanwhile try installing this version I've just compiled manually for you:
[MonoDevelop.WakaTime_1.0.6.zip](https://github.com/CodeCavePro/monodevelop-wakatime/files/938624/MonoDevelop.WakaTime_1.0.6.zip)

In case of further problems consider upgrading to v6.x with the above instructions or just wait for the solution

**Comment by salaros** [comment]
Just installed WakaTime 1.0.6 on MonoDevelop 5.9.6 on Ubuntu and it seems to work

![image](https://cloud.githubusercontent.com/assets/675348/25203814/5c5ddc7a-2563-11e7-8fe0-8ce2397b47d4.png)

I hope you will manage to install and use the addin too

**Comment by aaronfranke** [comment]
Thank you, that work-around does indeed work.

In case you forgot what year it was, it's April 2017 right now, March 2017 was one month ago...

**Comment by salaros** [comment]
I'm glad to hear it. Anyway it was March and August **2016** :) fixed my previous comment

**Comment by VansonLeung** [comment]
While using Unity's Monodevelop it tells me that Wakatime only supports 6.x, not 5.9.6 (missing dependencies). I don't think Unity Monodevelop will upgrade any time soon.

**Comment by VansonLeung** [comment]
Using your compiled 1.0.6 version works now. Thanks!

**Comment by xirc** [comment]
Your compiled 1.0.6 version works well with Unity's MonoDevelop 5.9.6. Thank you!

**Comment by tejasbedi1** [comment]
I had the same problem for Unity's MonoDevelop 5.9.6. Where version 2.02 Wakatime requires MoveDevelop 6.0 and above. Tried using your compiled 1.0.6 version. It does install and shows an update is available but i don't get an option to put in my API key. 
I am running a windows machine though.

**Comment by salaros** [comment]
Hi @tejasbedi1,

I'm really sorry you are experiencing this problem. Unfortunately I haven't managed to get help on MonoDevelop's Gitter: the addin gallery is broken, deprecated and non-supported.
I've tried creating new Git branches and creating updated builds, but the addin gallery's build system is stuck/broken. So I still have to provide you with manually compiled addins:

[MonoDevelop.WakaTime_1.0.7.zip](https://github.com/CodeCavePro/monodevelop-wakatime/files/1173284/MonoDevelop.WakaTime_1.0.7.zip)

I'm thinking of creating my own addin channel, which can be easily added to XS, MonoDevelop, Visual Studio for Mac etc

**Comment by tejasbedi1** [comment]
Thank You @salaros 
Your compiled plugin works like a charm.  I was about to switch to visual studio, but didn't want to do it mid-project. Thanks for saving me the hassle. Thank you very very much.

**Comment by salaros** [comment]
I'm glad I could help you, however it's really sad that Microsoft has abandoned MonoDevelop and it's addin server, which strangely is still used in their newer projects such as Visual Studio for Mac
MonoDevelop community on Gitter seems to be skeptic on perspective of getting the addin server working and keep suggesting me to host .mpack files elsewhere.

![image](https://user-images.githubusercontent.com/675348/28735874-fb57810c-73ef-11e7-8934-83dd10caf6f9.png)

![image](https://user-images.githubusercontent.com/675348/28735581-90f728ae-73ee-11e7-8ea9-a9b43c77620a.png)

**Comment by aaronfranke** [comment]
Microsoft doesn't care about MonoDevelop, they want you to buy their Visual Studio or Xamarin Studio.

**Comment by ryukinix** [comment]
That is so sad...
