### ISSUE TITLE
monodevelop lags and produces hundreds of python processes while holding button

### ISSUE THREAD

**Issue by ghost** [CodeCavePro/monodevelop-wakatime#8]
I often navigate trough big blocks of code with holding the down or up arrow, or replace blocks with alt+up/down within the code. I noticed that while wakatime is enabled, in these situations monodevelop starts to lag, sometime it hangs for a few seconds even. 

While looking at activity monitor, it is clear that a big bunch of python processes are generated. I'm guessing the addin sends a heartbeat every time a key repeats while press and hold.

I'm using osx 10.11.3 with unity-monodevelop 5.9.6, and the latest 1.0.5 wakatime addin.

Any idea how to resolve this? Thanks in advance!

**Comment by salaros** [comment]
Hi,
I think this issue is related to this commit: [Send heartbeat to WakaTime when position in doc changes ](https://github.com/CodeCavePro/monodevelop-wakatime/commit/ddaab45435e337a326dad0423ed4589d215d782a)
Anyway the heartbeats should not be sent too often, but with delays.
I will check this out as soon as I will get to my Linux laptop / MacBook and will report back.
Most likely it will take a couple of days, because I'm traveling now

**Comment by ghost** [comment]
Hi, thanks for looking into it! It seems to produce the same effect if I select a larger chunk of code and move it up or down, or toggle line comments to it. So maybe it's about the number of changed lines at a time, as well as the cursor thing.
Anyway, thanks for your help!

**Comment by salaros** [comment]
fixed in v1.0.6 release
